version: 1.0.{build}

image: Visual Studio 2022

# Define the build script
build_script:
  - ps: |
      # Check if running as Administrator
      $adminCheck = net session >nul 2>&1
      if ($?) {
          Write-Output "Administrator privileges are present."
      } else {
          Write-Output "Administrator privileges are not present."
      }

      # Check if Developer Mode is enabled
      $developerMode = Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock" -Name "AllowDevelopmentWithoutDevLicense" -ErrorAction SilentlyContinue
      if ($developerMode.AllowDevelopmentWithoutDevLicense -eq 1) {
          Write-Output "Developer Mode is enabled."
      } else {
          Write-Output "Developer Mode is not enabled."
      }

      # Check if SeCreateSymbolicLinkPrivilege is enabled
      $symlinkPrivilege = ((whoami /priv) -match "SeCreateSymbolicLinkPrivilege") -and ((whoami /priv) -match "Enabled")
      if ($symlinkPrivilege) {
          Write-Output "You have the required privileges to create symlinks."
      } else {
          Write-Output "You do not have the required privileges to create symlinks."
      }

      # Check if 'cat' program is installed
      if (Get-Command cat -ErrorAction SilentlyContinue) {
          Write-Output "The 'cat' program is installed."
      } else {
          Write-Output "The 'cat' program is not installed."
      }
