version: 1.0.{build}

image: Visual Studio 2022

# Define the build script
build_script:
  - cmd: >
      @echo off && net session >nul 2>&1 && echo Administrator privileges are present. || echo Administrator privileges are not present.

  - cmd: >
      @echo off && reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock" /v "AllowDevelopmentWithoutDevLicense" >nul 2>&1 && (reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock" /v "AllowDevelopmentWithoutDevLicense" | find "0x1" >nul 2>&1 && echo Developer Mode is enabled. || echo Developer Mode is not enabled.) || echo Developer Mode key not found, assuming not enabled.

  - cmd: >
      @echo off && whoami /priv > privileges.txt && (findstr /c:"SeCreateSymbolicLinkPrivilege" privileges.txt >nul 2>&1 && (findstr /c:"Enabled" privileges.txt >nul 2>&1 && echo You have the required privileges to create symlinks. || echo You do not have the required privileges to create symlinks.) || echo SeCreateSymbolicLinkPrivilege not found.) || echo SeCreateSymbolicLinkPrivilege check failed. && del privileges.txt

  - cmd: >
      @echo off && where cat >nul 2>&1 && (echo The 'cat' program is installed at: && where cat) || echo The 'cat' program is not installed.

  - cmd: >
      @echo off && exit 0
